export default [
  { setup: "Why did the React developer break up with JavaScript?", 
    punchline: "They wanted a little space between them.", 
    id : 1 },
  { setup: "Why don’t skeletons fight each other?", 
    punchline: "They don’t have the guts.",
    id : 2 },
  { setup: "Why did the CSS file go to therapy?", 
    punchline: "It had too many style issues.",
    id : 3 },
  { setup: "What do you call 8 hobbits?", 
    punchline: "A hobbyte.",
    id : 4 },
  { setup: "Why did the function cross the road?", 
    punchline: "To get to the other side effect.",
    id : 5 },
  { setup: "Why did the programmer quit their job?", 
    punchline: "Because they didn’t get arrays.",
    id : 6 },
  { setup: "Why did the HTML element go to school?", 
    punchline: "To get more class.",
    id : 7 },
  { setup: "Why was the JavaScript developer sad?", 
    punchline: "They didn’t know how to ‘null’ their feelings.",
    id : 8 },
  { setup: "Why did the computer keep sneezing?", 
    punchline: "It had a virus.",
    id : 9 },
  { setup: "Why was the math book sad?", 
    punchline: "It had too many problems.",
    id : 10 },
  { setup: "Why did the React developer break up with JavaScript?", 
    punchline: "They wanted a little space between them.", 
    id : 1 },
  { setup: "Why don’t skeletons fight each other?", 
    punchline: "They don’t have the guts.",
    id : 2 },
  { setup: "Why did the CSS file go to therapy?", 
    punchline: "It had too many style issues.",
    id : 3 },
  { setup: "What do you call 8 hobbits?", 
    punchline: "A hobbyte.",
    id : 4 },
  { setup: "Why did the function cross the road?", 
    punchline: "To get to the other side effect.",
    id : 5 },
  { setup: "Why did the programmer quit their job?", 
    punchline: "Because they didn’t get arrays.",
    id : 6 },
  { setup: "Why did the HTML element go to school?", 
    punchline: "To get more class.",
    id : 7 },
  { setup: "Why was the JavaScript developer sad?", 
    punchline: "They didn’t know how to ‘null’ their feelings.",
    id : 8 },
  { setup: "Why did the computer keep sneezing?", 
    punchline: "It had a virus.",
    id : 9 },
  { setup: "Why was the math book sad?", 
    punchline: "It had too many problems.",
    id : 10 }
];
